name: PR Checker

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR
        uses: actions/checkout@v6

      - name: Get list of changed files
        run: |
          CHANGED_FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }}..${{ github.sha }})
          echo "Changed files: $CHANGED_FILES"

          if [[ "$CHANGED_FILES" == *"README.md"* ]]; then
            echo "README.md file is allowed to change."
          else
            echo "Only README.md is allowed to change. Found changes in $CHANGED_FILES"
            exit 1
          fi
