name: PR checker

on:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Check for new files
        run: |
          ALLOWED_REGEX='^README\.md$'
          
          CHANGED_FILES=$(git diff --name-only origin/${{ github.event.pull_request.base.ref }}...HEAD)
          echo "Changed files: $CHANGED_FILES"

          INVALID=$(echo "$CHANGED_FILES" | grep -vE "$ALLOWED_REGEX" || true)

          if [ -n "$INVALID" ]; then
            echo "Only README.md is allowed to change. Found:"
            echo "$INVALID"
            exit 1
          fi